 local menu98edb85b00d9527ad5acebe451b3fae6 = {
     {"Application Finder", "xfce4-appfinder"},
     {"Archive Manager", "file-roller "},
     {"Atom", "env ATOM_DISABLE_SHELLING_OUT_FOR_ENVIRONMENT=false /usr/bin/atom ", "/usr/share//icons/hicolor/16x16/apps/atom.png" },
     {"Backup settings", "cronopete_preferences.sh"},
     {"Calculator", "gnome-calculator"},
     {"Characters", "/usr/bin/gnome-characters"},
     {"Clocks", "gnome-clocks"},
     {"Code - OSS", "/usr/bin/code-oss --no-sandbox --unity-launch ", "/usr/share/pixmaps/code-oss.png" },
     {"Cronopete: restore backup", "cronopete_restore.sh"},
     {"Disks", "gnome-disks"},
     {"Engrampa Archive Manager", "engrampa ", "/usr/share//icons/hicolor/16x16/apps/engrampa.png" },
     {"Files", "nautilus --new-window "},
     {"Fonts", "gnome-font-viewer "},
     {"HP Device Manager", "hp-toolbox", "///usr/share/hplip/data/images/128x128/hp_logo.png" },
     {"Kvantum Manager", "kvantummanager"},
     {"Manjaro User Guide", "/usr/bin/manjaro-documentation"},
     {"Maps", "gapplication launch org.gnome.Maps "},
     {"Mousepad", "mousepad "},
     {"Notable", "/opt/Notable/notable ", "/usr/share//icons/hicolor/16x16/apps/notable.png" },
     {"Notes", "bijiben "},
     {"Orage Globaltime", "globaltime", "/usr/share//icons/hicolor/48x48/apps/orage_globaltime.png" },
     {"Passwords and Keys", "seahorse"},
     {"Screenshot", "gnome-screenshot --interactive"},
     {"Screenshot", "xfce4-screenshooter", "/usr/share//icons/hicolor/48x48/apps/applets-screenshooter.png" },
     {"Software Token", "stoken-gui", "/usr/share/pixmaps/stoken-gui.png" },
     {"Software Token (small)", "stoken-gui --small", "/usr/share/pixmaps/stoken-gui.png" },
     {"Text Editor", "gedit "},
     {"Ulauncher", "env GDK_BACKEND=x11 /usr/bin/ulauncher --hide-window", "/usr/share//icons/hicolor/48x48/apps/ulauncher.svg" },
     {"Vim", "xterm -e vim ", "/usr/share//icons/hicolor/48x48/apps/gvim.png" },
     {"Xfburn", "xfburn"},
     {"balenaEtcher", "/opt/balenaEtcher/balena-etcher-electron ", "/usr/share//icons/hicolor/16x16/apps/balena-etcher-electron.png" },
 }

 local menu330f49df8243756a8a4dc7f7f7ee6dfe = {
     {"Atom", "env ATOM_DISABLE_SHELLING_OUT_FOR_ENVIRONMENT=false /usr/bin/atom ", "/usr/share//icons/hicolor/16x16/apps/atom.png" },
     {"CMake", "cmake-gui ", "/usr/share//icons/hicolor/32x32/apps/CMakeSetup.png" },
     {"Code - OSS", "/usr/bin/code-oss --no-sandbox --unity-launch ", "/usr/share/pixmaps/code-oss.png" },
     {"Electron", "electron ", "/usr/share/pixmaps/electron.png" },
     {"Electron", "electron6 ", "/usr/share/pixmaps/electron6.png" },
     {"Electron 4", "electron4 ", "/usr/share/pixmaps/electron4.png" },
     {"Icon Browser", "yad-icon-browser", "/usr/share//icons/hicolor/16x16/apps/yad.png" },
     {"Insomnia", "/opt/Insomnia/insomnia ", "/usr/share//icons/hicolor/16x16/apps/insomnia.png" },
     {"PhpStorm", "\"/opt/phpstorm/bin/phpstorm.sh\" ", "///opt/phpstorm/bin/phpstorm.png" },
     {"qgit", "qgit", "/usr/share//icons/hicolor/48x48/apps/qgit.png" },
 }

 local menude7a22a0c94aa64ba2449e520aa20c99 = {
     {"LibreOffice Math", "libreoffice --math ", "/usr/share//icons/hicolor/16x16/apps/libreoffice-math.png" },
 }

 local menud334dfcea59127bedfcdbe0a3ee7f494 = {
     {"Deepin Picker", "deepin-picker"},
     {"Document Scanner", "simple-scan"},
     {"GNU Image Manipulation Program", "gimp-2.10 ", "/usr/share//icons/hicolor/16x16/apps/gimp.png" },
     {"LibreOffice Draw", "libreoffice --draw ", "/usr/share//icons/hicolor/16x16/apps/libreoffice-draw.png" },
     {"Ristretto Image Viewer", "ristretto ", "/usr/share//icons/hicolor/16x16/apps/ristretto.png" },
     {"Shotwell", "shotwell ", "/usr/share//icons/hicolor/16x16/apps/shotwell.png" },
     {"gThumb", "gthumb ", "/usr/share//icons/hicolor/16x16/apps/org.gnome.gThumb.png" },
 }

 local menuc8205c7636e728d448c2774e6a4a944b = {
     {"Avahi SSH Server Browser", "/usr/bin/bssh"},
     {"Avahi VNC Server Browser", "/usr/bin/bvnc"},
     {"Brave", "brave ", "/usr/share/pixmaps/brave.png" },
     {"Discord", "/usr/bin/discord", "/usr/share/pixmaps/discord.png" },
     {"Empathy", "empathy", "/usr/share//icons/hicolor/16x16/apps/org.gnome.Empathy.png" },
     {"FileZilla", "filezilla", "/usr/share//icons/hicolor/16x16/apps/filezilla.png" },
     {"Google Chrome", "/usr/bin/google-chrome-stable ", "/usr/share//icons/hicolor/16x16/apps/google-chrome.png" },
     {"Keybase", "run_keybase ", "/usr/share//icons/hicolor/16x16/apps/keybase.png" },
     {"Mailspring", "/usr/bin/mailspring ", "/usr/share//icons/hicolor/16x16/apps/mailspring.png" },
     {"Popcorn Time", "popcorntime ", "/usr/share/pixmaps/popcorntime.png" },
     {"Slack", "/usr/bin/slack ", "/usr/share/pixmaps/slack.png" },
     {"TeamViewer", "/opt/teamviewer/tv_bin/script/teamviewer", "/usr/share//icons/hicolor/16x16/apps/TeamViewer.png" },
     {"Transmission", "transmission-gtk ", "/usr/share//icons/hicolor/16x16/apps/transmission.png" },
     {"X11VNC Server", "x11vnc -gui tray=setpass -rfbport PROMPT -bg -o %HOME/.x11vnc.log.%VNCDISPLAY", "/usr/share//icons/hicolor/32x32/status/computer.png" },
     {"Zoom", "/usr/bin/zoom ", "/usr/share/pixmaps/Zoom.png" },
     {"uGet", "env GDK_BACKEND=x11 uget-gtk ", "/usr/share//icons/hicolor/16x16/apps/uget-icon.png" },
 }

 local menu2f56b4f336dc97edf739bf79523fb9a6 = {
     {"Cheese", "cheese"},
     {"Kazam", "kazam", "/usr/share//icons/hicolor/16x16/apps/kazam.png" },
     {"Parole Media Player", "parole ", "/usr/share//icons/hicolor/16x16/apps/parole.png" },
     {"Popcorn Time", "popcorntime ", "/usr/share/pixmaps/popcorntime.png" },
     {"PulseAudio Equalizer", "pulseaudio-equalizer-gtk"},
     {"Qt V4L2 test Utility", "qv4l2", "/usr/share//icons/hicolor/16x16/apps/qv4l2.png" },
     {"Qt V4L2 video capture utility", "qvidcap", "/usr/share//icons/hicolor/16x16/apps/qvidcap.png" },
     {"VLC media player", "/usr/bin/vlc --started-from-file ", "/usr/share//icons/hicolor/16x16/apps/vlc.png" },
     {"Xfburn", "xfburn"},
 }

 local menudf814135652a5a308fea15bff37ea284 = {
     {"Adobe Reader 9", "acroread ", "/usr/share/pixmaps/acroread.png" },
     {"Antidote 10", "/usr/local/bin/Antidote10", "///usr/share/pixmaps/antidote10.png" },
     {"Connectix 10 - Antidote", "/opt/Druide/Connectix10/Application/Bin/AgentConnectix -oc", "///usr/share/pixmaps/agentconnectix10.png" },
     {"Dictionary", "xfce4-dict"},
     {"Documentation - Antidote 10", "xdg-open /opt/Druide/Antidote10/Documents", "///usr/share/pixmaps/antidote10.png" },
     {"LibreOffice", "libreoffice ", "/usr/share//icons/hicolor/16x16/apps/libreoffice-startcenter.png" },
     {"LibreOffice Base", "libreoffice --base ", "/usr/share//icons/hicolor/16x16/apps/libreoffice-base.png" },
     {"LibreOffice Calc", "libreoffice --calc ", "/usr/share//icons/hicolor/16x16/apps/libreoffice-calc.png" },
     {"LibreOffice Draw", "libreoffice --draw ", "/usr/share//icons/hicolor/16x16/apps/libreoffice-draw.png" },
     {"LibreOffice Impress", "libreoffice --impress ", "/usr/share//icons/hicolor/16x16/apps/libreoffice-impress.png" },
     {"LibreOffice Math", "libreoffice --math ", "/usr/share//icons/hicolor/16x16/apps/libreoffice-math.png" },
     {"LibreOffice Writer", "libreoffice --writer ", "/usr/share//icons/hicolor/16x16/apps/libreoffice-writer.png" },
     {"Microsoft Office Online", "ms-office-online", "///usr/share/pixmaps/ms-office.png" },
     {"Orage Calendar", "orage", "/usr/share//icons/hicolor/48x48/apps/xfcalendar.png" },
     {"Orage Globaltime", "globaltime", "/usr/share//icons/hicolor/48x48/apps/orage_globaltime.png" },
     {"PDF Arranger", "pdfarranger ", "/usr/share//icons/hicolor/16x16/apps/pdfarranger.png" },
     {"Zathura", "zathura ", "/usr/share//icons/hicolor/16x16/apps/org.pwmt.zathura.png" },
 }

 local menua45da96d0bf6575970f2d27af22be28a = {
     {"Avahi Zeroconf Browser", "/usr/bin/avahi-discover"},
     {"Bulk Rename", "/usr/lib/Thunar/ThunarBulkRename ", "/usr/share//icons/hicolor/16x16/apps/Thunar.png" },
     {"Color Profile Viewer", "gcm-viewer", "/usr/share//icons/hicolor/16x16/apps/gnome-color-manager.png" },
     {"Disk Usage Analyzer", "baobab"},
     {"GParted", "/usr/bin/gparted ", "/usr/share//icons/hicolor/16x16/apps/gparted.png" },
     {"Hardware Locality lstopo", "lstopo"},
     {"Htop", "xterm -e htop", "/usr/share/pixmaps/htop.png" },
     {"Kitematic", "kitematic"},
     {"LXTerminal", "lxterminal", "/usr/share//icons/hicolor/128x128/apps/lxterminal.png" },
     {"Manage Printing", "/usr/bin/xdg-open http://localhost:631/", "/usr/share//icons/hicolor/16x16/apps/cups.png" },
     {"Manjaro Hello", "/usr/bin/manjaro-hello", "/usr/share//icons/hicolor/16x16/apps/manjaro.png" },
     {"NordPy", "\"/usr/share/NordPy/nordpy.py\"", "///usr/share/NordPy/media/nordvpn.png" },
     {"OpenJDK Java 13 Console", "/usr/lib/jvm/java-13-openjdk/bin/jconsole"},
     {"OpenJDK Java 13 Shell", "xterm -e /usr/lib/jvm/java-13-openjdk/bin/jshell"},
     {"SUSE Studio Imagewriter", "imagewriter ", "/usr/share//icons/hicolor/32x32/apps/imagewriter.png" },
     {"Sensor Viewer", "xfce4-sensors", "/usr/share//icons/hicolor/24x24/apps/xfce-sensors.png" },
     {"System Log", "gnome-system-log", "/usr/share//icons/hicolor/16x16/apps/logview.png" },
     {"System Monitor", "gnome-system-monitor"},
     {"Task Manager", "xfce4-taskmanager"},
     {"Terminal", "gnome-terminal"},
     {"Terminator", "terminator", "/usr/share//icons/hicolor/16x16/apps/terminator.png" },
     {"Thunar File Manager", "thunar ", "/usr/share//icons/hicolor/16x16/apps/Thunar.png" },
     {"Timeshift", "timeshift-launcher", "/usr/share//icons/hicolor/16x16/apps/timeshift.png" },
     {"Xfce Terminal", "xfce4-terminal"},
     {"dconf Editor", "dconf-editor", "/usr/share//icons/hicolor/16x16/apps/ca.desrt.dconf-editor.png" },
 }

xdgmenu = {
    {"Accessories", menu98edb85b00d9527ad5acebe451b3fae6},
    {"Development", menu330f49df8243756a8a4dc7f7f7ee6dfe},
    {"Education", menude7a22a0c94aa64ba2449e520aa20c99},
    {"Graphics", menud334dfcea59127bedfcdbe0a3ee7f494},
    {"Internet", menuc8205c7636e728d448c2774e6a4a944b},
    {"Multimedia", menu2f56b4f336dc97edf739bf79523fb9a6},
    {"Office", menudf814135652a5a308fea15bff37ea284},
    {"System", menua45da96d0bf6575970f2d27af22be28a},
}

